# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    access_denied_url: /index
    role_hierarchy:
        ROLE_Sales:       [ROLE_Guest]
        ROLE_Admin:       [ROLE_Sales]
        ROLE_ADMIN:       [ROLE_Admin]
    encoders:
        DatabaseBundle\Entity\Account:
            id: ipx_password_encoder

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        db_provider:
            entity:
                class: DatabaseBundle:Account
                property: username

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    #providers:
    #    in_memory:
    #        memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~
            http_basic: ~
            access_denied_url: /login
            form_login:
                default_target_path: /index
                always_use_default_target_path: true
                login_path: /index
                check_path: /login_check
                failure_path: /index
            logout:
                path:   /logout
                target: /index

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
            - { path: ^/index, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/explore, roles: ROLE_Guest }
            - { path: ^/add, roles: ROLE_Admin}
            - { path: ^/, roles: ROLE_Guest }
